CREATE DATABASE IF NOT EXISTS ecommerce;
CREATE DATABASE IF NOT EXISTS retailler;

USE ecommerce;

CREATE TABLE IF NOT EXISTS apadd (
  Apid INT PRIMARY KEY AUTO_INCREMENT,
  apname VARCHAR(100) NOT NULL,
  apbrand VARCHAR(100) DEFAULT NULL,
  apcategory VARCHAR(100) DEFAULT NULL,
  apqty INT DEFAULT 0,
  apprice DECIMAL(10,2) DEFAULT 0.00,
  apimage VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS aregister (
  aid INT PRIMARY KEY AUTO_INCREMENT,
  aname VARCHAR(100) NOT NULL,
  aadd VARCHAR(255) DEFAULT NULL,
  apass VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cregister (
  Cid INT PRIMARY KEY AUTO_INCREMENT,
  Cname VARCHAR(100) NOT NULL,
  Cemail VARCHAR(150) DEFAULT NULL,
  Cadd VARCHAR(255) DEFAULT NULL,
  Ccontact VARCHAR(20) DEFAULT NULL,
  Cpass VARCHAR(255) NOT NULL,
  Cconpass VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  oid INT PRIMARY KEY AUTO_INCREMENT,
  pid INT DEFAULT NULL,
  cid INT DEFAULT NULL,
  cost DECIMAL(10,2) DEFAULT 0.00,
  source VARCHAR(255) DEFAULT NULL,
  destination VARCHAR(255) DEFAULT NULL
);

USE retailler;

CREATE TABLE IF NOT EXISTS rpadd (
  Rpid INT PRIMARY KEY AUTO_INCREMENT,
  Rpname VARCHAR(100) NOT NULL,
  Rpbrand VARCHAR(100) DEFAULT NULL,
  Rpqty INT DEFAULT 0,
  Rpprice DECIMAL(10,2) DEFAULT 0.00
);

CREATE TABLE IF NOT EXISTS rregister (
  rid INT PRIMARY KEY AUTO_INCREMENT,
  rname VARCHAR(100) NOT NULL,
  radd VARCHAR(255) DEFAULT NULL,
  rpass VARCHAR(255) NOT NULL,
  rconpass VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS product (
  pid INT PRIMARY KEY AUTO_INCREMENT,
  pname VARCHAR(100) NOT NULL,
  pbrand VARCHAR(100) DEFAULT NULL,
  pqty INT DEFAULT 0,
  pprice DECIMAL(10,2) DEFAULT 0.00,
  pimage VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  oid INT PRIMARY KEY AUTO_INCREMENT,
  pid INT DEFAULT NULL,
  cid INT DEFAULT NULL,
  cost DECIMAL(10,2) DEFAULT 0.00,
  source VARCHAR(255) DEFAULT NULL,
  destination VARCHAR(255) DEFAULT NULL
);
